# Generated by Django 5.0.6 on 2024-07-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mensaje_mensaje_respuesta_tarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='creador',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
