# Generated by Django 5.0.6 on 2024-07-05 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_comentario_autor_alter_proyecto_creador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_vencimiento',
            new_name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignada_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
