# Generated by Django 5.0.6 on 2024-07-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_perfil_avatar_perfil_facebook_perfil_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bio',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='location',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
