# Generated by Django 5.0.6 on 2024-07-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='mensaje_respuesta',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
