# Generated by Django 5.0.6 on 2024-07-06 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_mensaje_mensaje_respuesta_mensaje_leido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
