# Generated by Django 5.0.6 on 2024-07-07 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_perfil_educacion1_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='myapp.tarea')),
            ],
        ),
    ]
