# Generated by Django 5.0.6 on 2024-07-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_descripcion_seguimientotarea_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='myapp.tarea')),
            ],
        ),
    ]
