# Generated by Django 5.0.6 on 2024-07-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_comentariotarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
    ]
