# Generated by Django 5.0.6 on 2024-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_proyecto_categoria_alter_proyecto_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
