# Generated by Django 5.0.6 on 2024-07-08 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_educacion_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
