# Generated by Django 5.0.6 on 2024-07-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_postulacion_estado_alter_postulacion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
