# Generated by Django 5.0.6 on 2024-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_educacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_mensajes/'),
        ),
    ]
