# Generated by Django 5.0.6 on 2024-07-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_mensaje_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='imagen',
        ),
    ]
