# Generated by Django 5.0.6 on 2024-08-03 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_mensaje_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionOculta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_oculto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocultado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'usuario_oculto')},
            },
        ),
    ]
