# Generated by Django 5.0.6 on 2024-08-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0040_conversacionoculta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="experiencia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="habilidades",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("tecnologia", "Tecnología"),
                    ("educacion", "Educación"),
                    ("salud", "Salud"),
                    ("finanzas", "Finanzas"),
                    ("energia", "Energía"),
                    ("animales", "Animales"),
                ],
                default="tecnologia",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "especialista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="myapp.perfil",
                    ),
                ),
            ],
        ),
    ]
