# Generated by Django 5.0.6 on 2024-08-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_perfil_experiencia_perfil_habilidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
