# Generated by Django 5.0.6 on 2024-08-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_notificacion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.CharField(default='/mensajes/', max_length=200),
        ),
    ]
