# Generated by Django 5.0.6 on 2024-08-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0043_alter_notificacion_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="disponibilidad",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="especialidad",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
