# Generated by Django 5.0.6 on 2024-08-07 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0044_perfil_disponibilidad_perfil_especialidad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="colaboradores",
            field=models.ManyToManyField(
                blank=True,
                related_name="proyectos_colaborados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
